spring.application.name=stock-service
server.port=2222

spring.datasource.url=jdbc:postgresql://localhost:5432/stock-service
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.pattern.console=%c :%p  -->%m : %M :: %d  %n
logging.file.name=logger/log.txt
logging.pattern.file=%c :%p  -->%m : %M :: %d  %n



